### ISSUE TITLE
无法打开rxposed,黑屏

### ISSUE THREAD

**Issue by QAQQL** [Thehepta/rxposed#17]
小米
系统: MIUI14 v14.0.23.10.15.dev
安卓: 13
使用面具授权rxposed软件root后.重启rxposed,所有应用均卡死

**Comment by QAQQL** [comment]
使用最新的release的测试版

**Comment by Thehepta** [comment]
是否安装了zygisk 这类模块，这会与rxposed冲突导致应用开死。

**Comment by QAQQL** [comment]
了解,关闭lsp,使用rxposed是吧
