### ISSUE TITLE
使用这个框架情况下，打开市面的环境检测工具都会直接闪退重启手机

### ISSUE THREAD

**Issue by orzlenmo** [Thehepta/RXPosed#25]
使用环境：
小米10 ultra
miui 14.0.2   android 13版本
正常安装注入这个框架，一旦打开momo 、牛头人(nativeTest)、hunter_5.8.4.apk,这些检测环境是否异常的软件一打开就出现闪退自动重启手机的情况，希望作者能回答下为什么

**Comment by orzlenmo** [comment]
补充下，上面闪退自动重启手机后，注入没了以后再打开momo就，出现异常了
![Screenshot_2024-10-17-15-18-42-612_io github vvb2060 mahoshojo](https://github.com/user-attachments/assets/fa46ed54-a792-41e7-9760-2de6cd0c3ce4)

**Comment by Thehepta** [comment]
是否看过文档，同类型软件冲突，不能装zygisk 这些。另外，不是只会触发检测软件崩溃，而是所有的软件都会崩溃。正常注入，我日常使用小米14.07 android13 ，一直正常。

**Comment by orzlenmo** [comment]
之前用的apatch lsposed，后面想试试你这个，就把那些模块先关掉了，我正常使用也没问题，但是我想看看momo 、牛头人(nativeTest)、hunter_5.8.4.apk 这些检测环境软件能不能安全过检测，所以就打开他们了，按你的意思是这类检测软件有可能跟你这个框架冲突闪退是把？上次试你这个确实可以过taobao检测，taobao的我原来lsposed 的模块作用上去，就会黑号，用你这个框架+模块没问题，其实我就是想验证下你这个框架是否能过这些平台app的检测啦

**Comment by Thehepta** [comment]
恩，你的操作没有问题，zygisk模块关闭使用rxp没有任何问题。
这些检测软件崩溃我确实没有预料到，我以前试过hunter是没有问题。另外可能是iso进程我没处理，也有可能是别的东西检测到了。

感谢你的提供的信息，非常重要。不过最近没啥时间解决，可能要过一段时间解决

**Comment by orzlenmo** [comment]
可以的，感谢大佬的回复。正常使用没啥问题的，我也会继续体验这个框架。
