### ISSUE TITLE
XiaoMi 8 刷机成 Pixel Experience Android 13 并使用Magisk Root， 然后rxposed激活会导致手机重启的问题(已解决)

### ISSUE THREAD

**Issue by GamePlug** [Thehepta/RXPosed#28]
![image](https://github.com/user-attachments/assets/9318b570-26f4-4f84-8678-0704bd29d496)

经过调试发现红色框框这段代码会导致手机重启并且激活会失败，大概率是手机系统问题，注释掉后激活成功，测试注入功能也正常，暂时没发现什么问题

**Comment by Thehepta** [comment]
额，这段代码是 注入zygote 的，zygote 一共有两个进程，zygote64 和zygote，除非你手机不不支持32位，否则必有zygote。
你调试把我代码拉下来直接运行，是没有没有32位的库的，所以会报错，需要先编译完整的apk文件，然后安装进去。

验证的方法就是直接下载我编译好的apk文件。里面有这个代码可以直接运行

**Comment by GamePlug** [comment]
![image](https://github.com/user-attachments/assets/b2749b47-f8e3-4c0d-9e95-4f2ca265cff4)

@Thehepta 感谢解答，确实是你说的这样，打包好再安装或者安装你打包好的apk没问题，我查了一下直接运行代码需要手动选择加载64位还是32位
