### ISSUE TITLE
android 14激活后卡住

### ISSUE THREAD

**Issue by blueb0ne** [Thehepta/RXPosed#29]
```
11-05 15:22:33.218: I/ActivityManager(1926): Start proc 9282:hepta.rxposed.manager/u0a259 for next-top-activity {hepta.rxposed.manager/hepta.rxposed.manager.MainActivity}
11-05 15:22:33.219: E/Zygote(9282): System zygote died with fatal exception
11-05 15:22:33.219: E/Zygote(9282): java.lang.NoSuchMethodError: no static method "Lcom/android/internal/os/Zygote;.nativeSpecializeAppProcess(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ)V"
11-05 15:22:33.219: E/Zygote(9282): 	at com.android.internal.os.ZygoteCommandBuffer.nativeForkRepeatedly(Native Method)
11-05 15:22:33.219: E/Zygote(9282): 	at com.android.internal.os.ZygoteCommandBuffer.forkRepeatedly(ZygoteCommandBuffer.java:169)
11-05 15:22:33.219: E/Zygote(9282): 	at com.android.internal.os.Zygote.forkSimpleApps(Zygote.java:716)
11-05 15:22:33.219: E/Zygote(9282): 	at com.android.internal.os.ZygoteConnection.processCommand(ZygoteConnection.java:287)
11-05 15:22:33.219: E/Zygote(9282): 	at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:521)
11-05 15:22:33.219: E/Zygote(9282): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
11-05 15:22:33.219: D/AndroidRuntime(9282): Shutting down VM
11-05 15:22:33.225: E/OpenGLRenderer(2660): Unable to match the desired swap behavior.

```

**Comment by blueb0ne** [comment]
11-05 15:22:33.276: I/crash_dump64(9286): obtaining output fd from tombstoned, type: kDebuggerdTombstoneProto
11-05 15:22:33.277: I/tombstoned(857): received crash request for pid 9282
11-05 15:22:33.278: I/crash_dump64(9286): performing dump of process 9282 (target tid = 9282)
11-05 15:22:33.324: I/GsaVoiceInteractionSrv(3903): Handling ACTION_STOP_HOTWORD
11-05 15:22:33.339: W/ProcessStats(1926): Tracking association SourceState{bc597f6 com.google.android.googlequicksearchbox:search/10152 BTop #4968} whose proc state 2 is better than process ProcessState{b50f863 com.google.android.googlequicksearchbox:interactor/10152 pkg=com.google.android.googlequicksearchbox} proc state 4 (133 skipped)
11-05 15:22:33.362: A/DEBUG(9286): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-05 15:22:33.362: A/DEBUG(9286): Build fingerprint: 'google/redfin/redfin:14/UP1A.231105.001.B2/11260668:user/release-keys'
11-05 15:22:33.362: A/DEBUG(9286): Revision: 'MP1.0'
11-05 15:22:33.362: A/DEBUG(9286): ABI: 'arm64'
11-05 15:22:33.362: A/DEBUG(9286): Timestamp: 2024-11-05 15:22:33.291615892+0800
11-05 15:22:33.362: A/DEBUG(9286): Process uptime: 1s
11-05 15:22:33.362: A/DEBUG(9286): Cmdline: zygote64
11-05 15:22:33.362: A/DEBUG(9286): pid: 9282, tid: 9282, name: Shutdown thread  >>> zygote64 <<<
11-05 15:22:33.362: A/DEBUG(9286): uid: 0
11-05 15:22:33.362: A/DEBUG(9286): signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-05 15:22:33.362: A/DEBUG(9286): Abort message: 'No pending exception expected: java.lang.NoSuchMethodError: no static method "Lcom/android/internal/os/Zygote;.nativeSpecializeAppProcess(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ)V"
11-05 15:22:33.362: A/DEBUG(9286):   at boolean com.android.internal.os.ZygoteCommandBuffer.nativeForkRepeatedly(long, int, int, int, java.lang.String) (ZygoteCommandBuffer.java:-2)
11-05 15:22:33.362: A/DEBUG(9286):   at boolean com.android.internal.os.ZygoteCommandBuffer.forkRepeatedly(java.io.FileDescriptor, int, int, java.lang.String) (ZygoteCommandBuffer.java:169)
11-05 15:22:33.362: A/DEBUG(9286):   at java.lang.Runnable com.android.internal.os.Zygote.forkSimpleApps(com.android.internal.os.ZygoteCommandBuffer, java.io.FileDescriptor, int, int, java.lang.String) (Zygote.java:716)
11-05 15:22:33.362: A/DEBUG(9286):   at java.lang.Runnable com.android.internal.os.ZygoteConnection.processCommand(com.android.internal.os.ZygoteServer, boolean) (ZygoteConnection.java:287)
11-05 15:22:33.362: A/DEBUG(9286):   at java.lang.Runnable com.android.internal.os.ZygoteServer.runSelectLoop(java.lang.String) (ZygoteServer.java:521)
11-05 15:22:33.362: A/DEBUG(9286):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:958)'
11-05 15:22:33.362: A/DEBUG(9286):     x0  0000000000000000  x1  0000000000002442  x2  0000000000000006  x3  0000007fd3105840
11-05 15:22:33.362: A/DEBUG(9286):     x4  607372652c271f63  x5  607372652c271f63  x6  607372652c271f63  x7  7f7f7f7f7f7f7f7f
11-05 15:22:33.362: A/DEBUG(9286):     x8  00000000000000f0  x9  0000007d76e76090  x10 0000000000000001  x11 0000007d76ebc058
11-05 15:22:33.362: A/DEBUG(9286):     x12 0000000000026c52  x13 fc4aa7c88348cfb9  x14 0000000000000000  x15 0000000000000003
11-05 15:22:33.362: A/DEBUG(9286):     x16 0000007d76f20d08  x17 0000007d76efde90  x18 0000007d795e4000  x19 0000000000002442
11-05 15:22:33.362: A/DEBUG(9286):     x20 0000000000002442  x21 00000000ffffffff  x22 0000007d792df005  x23 0000007d69eb2ca0
11-05 15:22:33.362: A/DEBUG(9286):     x24 0000007d792df019  x25 0000007d792f4000  x26 0000000000000001  x27 0000007d69eb2000
11-05 15:22:33.362: A/DEBUG(9286):     x28 431bde82d7b634db  x29 0000007fd31058c0
11-05 15:22:33.362: A/DEBUG(9286):     lr  0000007d76ead9b8  sp  0000007fd3105820  pc  0000007d76ead9e4  pst 0000000000001000
11-05 15:22:33.362: A/DEBUG(9286): 5 total frames
11-05 15:22:33.362: A/DEBUG(9286): backtrace:
11-05 15:22:33.362: A/DEBUG(9286):       #00 pc 00000000000599e4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: c74277f481a383c87215b672f6465e24)
11-05 15:22:33.362: A/DEBUG(9286):       #01 pc 000000000006ed94  /apex/com.android.runtime/lib64/bionic/libc.so (__stack_chk_fail+20) (BuildId: c74277f481a383c87215b672f6465e24)
11-05 15:22:33.362: A/DEBUG(9286):       #02 pc 00000000000e591c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+1184) (BuildId: ff3670cd8e0afe5f1936322ffd554eea)
11-05 15:22:33.362: A/DEBUG(9286):       #03 pc 000000000000252c  /system/bin/app_process64 (main+1240) (BuildId: 230f6308c649f3833f4685a2a2c30c51)
11-05 15:22:33.362: A/DEBUG(9286):       #04 pc 0000000000052610  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: c74277f481a383c87215b672f6465e24)
11-05 15:22:33.369: E/tombstoned(857): Tombstone written to: tombstone_12
11-05 15:22:33.370: E/NativeTombstoneManager(1926): Tombstone's UID (0) not an app, ignoring
11-05 15:22:33.373: E/NativeTombstoneManager(1926): Tombstone's UID (0) not an app, ignoring
11-05 15:22:33.377: I/Zygote(1048): Process 9282 exited due to signal 6 (Aborted)

**Comment by Thehepta** [comment]
嗯，看rom指纹确实是14,但是14的我看了下，不应该有这个问题啊，你这是p5吧，还是原生系统，我对照着源码适配过的。
你check一下，发一下check界面

**Comment by Thehepta** [comment]
另外最好把framework.jar 文件也发一下

**Comment by Thehepta** [comment]
。。。
